Leo_SubStr:Leo_and_SubStr.o
        gcc -o Leo_SubStr ./Leo_and_SubStr.o

Leo_and_SubStr.o:Leo_and_SubStr.c
        gcc -c -g -Wall -o Leo_and_SubStr.o ./Leo_and_SubStr.c

clean:
        rm -rf Leo_and_SubStr.o
        rm -rf Leo_SubStr
